name: "[sepolia-deploy] manage strategy keeper"
on:
  workflow_dispatch:
    inputs:
      keeper:
        description: 'keeper address'
        required: true
        default: '0x'
      strategy:
        description: 'strategy address'
        required: true
        default: '0x'
  
    
jobs:
  acceptManagement:
    runs-on: ubuntu-latest
    environment: 
      name: sepolia
      url: https://term-finance.github.io/yearn-v3-term-vault/
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
      - run: forge install
      - run: forge build
      - run: forge tree
      - run: forge script script/StrategyKeeperManagement.s.sol:StrategyKeeperManagement --rpc-url $RPC_URL --broadcast --gas-price  500000000000  --verify --verbosity 4
        env:
          RPC_URL:  ${{ secrets.RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          KEEPER_ADDRESS: ${{ github.event.inputs.keeper }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          STRATEGY: ${{ github.event.inputs.strategy }}
  