name: "[sepolia-deploy] deploy mock vault"
on:
  workflow_dispatch:
    inputs:
      vaultToken:
        description: 'Vault token address'
        required: true
        default: '0x'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: sepolia
      url: https://term-finance.github.io/yearn-v3-term-vault/
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - run: forge install
      - run: forge build
      - run: forge tree
      - name: Verify Environment
        run: |
          if [ -z "$PRIVATE_KEY" ]; then
            echo "PRIVATE_KEY is not set"
          else
            echo "PRIVATE_KEY is set and starts with: ${PRIVATE_KEY:0:6}..."
          fi
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      - name: Deploy Mock Vault
        run: |
          forge create lib/openzeppelin-contracts/contracts/mocks/ERC4626Mock.sol:ERC4626Mock \
          --rpc-url "$RPC_URL" \
          --private-key "$PRIVATE_KEY" \
          --constructor-args "$VAULT_TOKEN" \
          --etherscan-api-key "$ETHERSCAN_API_KEY" \
          --verify
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          VAULT_TOKEN: ${{ github.event.inputs.vaultToken }}